sudo: required
language: generic

services:
  - docker

# Commands to run before the main build
before_install:
  # Build the Docker image using the Dockerfile.dev file and tag it
  - docker build -t vinit003/docker-react -f Dockerfile.dev .

# Commands to run the actual build and tests
script:
  # Run the tests inside a Docker container created from the image built above
  - docker run -e CI=true vinit003/docker-react npm run test

# Deploy to AWS Elastic Beanstalk
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-767397890053"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
