# Use sudo-enabled infrastructure
sudo: required

# Specify that we need Docker as a service
services:
  - docker

# Environment variables
env:
  global:
    - IMAGE_TAG="build-${TRAVIS_COMMIT}-$(date +'%Y%m%d%H%M%S')"
    - REACT_APP_IMAGE_TAG=${IMAGE_TAG}

# Commands to run before the main build
before_install:
  # Echo environment variables to log for verification
  - echo "Starting build for commit:" ${TRAVIS_COMMIT}
  - echo "Date and Time:" $(date)
  
  # Echo building Docker image with tag
  - echo "Building Docker image with tag:" ${IMAGE_TAG}
  
  # Build the Docker image using the Dockerfile.dev file and tag it
  - docker build -t vinit003/docker-react:${IMAGE_TAG} --build-arg REACT_APP_IMAGE_TAG=${REACT_APP_IMAGE_TAG} -f Dockerfile.dev .
  
  # Echo that Docker build completed and show Docker image details
  - echo "Docker build completed."
  - docker images vinit003/docker-react:${IMAGE_TAG}

# Commands to run the actual build and tests
script:
  # Echo checking versions for debugging
  - echo "Checking Node and NPM versions"
  
  # Displaying Node, NPM versions
  - docker run vinit003/docker-react:${IMAGE_TAG} node --version
  - docker run vinit003/docker-react:${IMAGE_TAG} npm --version
  
  # Display React version or echo not found if the command fails
  - docker run vinit003/docker-react:${IMAGE_TAG} npm list react || echo "React not found"
  
  # Echo running tests in Docker container
  - echo "Running tests in Docker container"
  
  # Run tests and display the result
  - docker run -e CI=true vinit003/docker-react:${IMAGE_TAG} npm run test
  - echo "Tests completed."

# Display IMAGE_TAG and all environment variables before deployment
before_deploy:
  - echo "Preparing to deploy. IMAGE_TAG=${IMAGE_TAG}"
  - echo "Current Environment Variables:"
  - printenv | sort

# Deploy to AWS Elastic Beanstalk
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-767397890053"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  version: "${IMAGE_TAG}"
  skip_cleanup: true
  wait-until-deployed: true

after_deploy:
  - echo "Deployment completed successfully."
