version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: "frontend"
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: "frontend_test"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command: ["npm", "run", "test"]
