# Use the latest Node.js version based on Alpine Linux
FROM node:16-alpine
# Link: https://stackoverflow.com/questions/75338297/docker-build-on-nodealpine-lts-suddenly-not-working-anymore
# FROM node@sha256:db4b1d98b5a92263f2b9221c4d7930ce6b02f9834926c8b6174bfed2913cea16

# Set the user to 'node' for better security
USER node

# Create and set the working directory
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# Copy the package.json and package-lock.json files to the working directory
COPY --chown=node:node ./package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY --chown=node:node ./ ./


# Start the application
CMD ["npm", "start"]
