version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_IMAGE_TAG: ${REACT_APP_IMAGE_TAG}  # Ensure this is correct
    ports:
      - "80:80"
    environment:
      - REACT_APP_IMAGE_TAG=${REACT_APP_IMAGE_TAG}  # Pass environment variable
    deploy:
      resources:
        limits:
          memory: 2048M  # Adjust as needed