# Use the latest Node.js version based on Alpine Linux
FROM node:16-alpine as builder

# Set the user to 'node' for better security
USER node

# Create and set the working directory
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

# Copy the package.json and package-lock.json files to the working directory
COPY --chown=node:node ./package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY --chown=node:node ./ ./


# Start the application
CMD ["npm", "start"]
